# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e57dbdf485ccc78813eaee122adaaa7b10e66551fe0eb942325fb83a262037e95c16cba295e1c74e973caaeeadd48fe0bbb1f57b2bcafbfe1684a713aa3f8c61

test:
  secret_key_base: 02d186e5b78a5206886ab9f9e30d26916f384355b53f084a858e5c84c487c34bdc92ce2526610736bed1cb86c1c597e179ef93e8e93f0c749c66f938ed523015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
